package controller;

public enum MenuTypesGraphic {
    SIGNUPCONTROLLERGRAPHIC,
    SCOREBOARDCONTROLLERDGRAPHIC,
    PROFILECONTROLLERGRAPHIC,
    LOGINCONTROLLERGRAPHIC,
    CHANGEPASSWORDCONTROLLERGRAPHIC,
    CHANGENICKNAMECONTROLLERGRAPHIC,
    MAINCONTROLLERGRAPHIC
}
