package model;

public enum TakeActionCase {
    SUMMONED,
    REMOVE_FROM_MONSTERZONE,
    ATTACKED,
    FLIP_SUMMONED,
    SPECIAL_SUMMONED,
    DIED_BY_BEING_ATTACKED,
    PUT_IN_MONSTERZONE,
    PUT_IN_SPELLTRAPZONE,
    REMOVE_FROM_SPELLTRAPZONE,
    TURN_START;
//    RITUAL_SUMMONED
}
